#!/usr/bin/env bash
path=src/main/webapp/
cssPath="/uii/templatePG/css/"
declare -a sources=("${path}/uii/templatePG/css/src/" "${path}/uii/templatePG/css/lib/" "${path}/uii/templatePG/js/")

runBuild() {
    checkModules
    npm run build --prefix $path
}

runInstall() {
    npm ci --prefix $path
    runBuild
}

checkModules() {
    if [ ! -d "${path}node_modules" ]; then
        echo "Node modules not found. Running npm install..."
        runInstall
        exit 0
    fi
}

checkAssets() {
    if [ ! -f "${path}dist/js/main.js" ]; then
        echo "Compiled JS not found. Running npm build..."
        runBuild
        exit 0
    elif [ ! -f "${path}${cssPath}dist/main.min.css" ]; then
        echo "Compiled CSS not found. Running npm build..."
        runBuild
        exit 0
    elif [ ! -f "${path}${cssPath}dist/bootstrap.min.css" ]; then
        echo "Compiled BS CSS not found. Running npm build..."
        runBuild
        exit 0
    fi
}

CheckIfChanged() {
    for i in "${sources[@]}"
    do
        if echo git diff --name-only HEAD@{1} HEAD -- | grep --quiet "$i"; then
            echo "Changes detected at $i"
            runBuild
            exit 0
        else
            echo "No changes detected at $i"
        fi
    done
    echo "No changes detected in any source files"
}

CheckIfPresent() {
    checkAssets
    checkModules
    echo "Compiled assets found. Checking for changes..."
}

CheckIfPresent
CheckIfChanged
