---
services:
  workflow:
    image: intranda/goobi-workflow:latest
    depends_on:
      - workflow-db
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_HOST: workflow-db
      DB_NAME: goobi
      DB_USER: goobi
      DB_PORT: 3306
      DB_PASSWORD: CHANGEME
      PW_GOOBITESTUSER: CHANGEME
      # Configure the goobi_config.properties using the schema GOOBI_<var_name>
      # All possible variables can be found here https://docs.goobi.io/de/workflow/manual/admin/config_files/goobi_config.properties
      GOOBI_ApplicationHeaderTitle: "Goobi workflow"
    volumes:
      - type: bind
        source: ./goobi/config
        target: /opt/digiverso/goobi/config
      - type: bind
        source: ./goobi/plugins
        target: /opt/digiverso/goobi/plugins
      - type: bind
        source: .ge/tomcat/logs
        target: /usr/local/tomcat/logs

  workflow-db:
    image: mariadb:lts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: goobi
      MYSQL_USER: goobi
      MYSQL_PASSWORD: CHANGEME
      TZ: "Europe/Berlin"
    volumes:
      - type: bind
        source: ./db/setup
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/mysql
        target: /var/lib/mysql