package de.sub.goobi.forms;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

import javax.faces.model.SelectItem;

import org.junit.Test;

public class AdditionalFieldTest {

    @Test
    public void testConstructor() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        assertNotNull(af);
    }

    @Test
    public void testInitStart() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setInitStart(null);
        af.setInitStart("start");
        assertEquals("start", af.getInitStart());
    }

    @Test
    public void testInitEnd() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setInitEnd(null);
        af.setInitEnd("end");
        assertEquals("end", af.getInitEnd());
    }

    @Test
    public void testTitle() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setTitel("title");
        assertEquals("title", af.getTitel());
    }

    @Test
    public void testValue() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setWert("Value");
        assertEquals("Value", af.getWert());
    }

    @Test
    public void testFrom() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        assertNotNull(af.getFrom());
        assertEquals("prozess", af.getFrom());
        af.setFrom("from");
        assertEquals("from", af.getFrom());
    }

    @Test
    public void testSelectList() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        List<SelectItem> list = new ArrayList<SelectItem>();
        list.add(new SelectItem("value", "label"));
        af.setSelectList(list);
        assertEquals(list, af.getSelectList());
    }

    @Test
    public void testRequired() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        assertFalse(af.isRequired());
        af.setRequired(true);
        assertTrue(af.isRequired());
    }

    @Test
    public void testUghbinding() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        assertFalse(af.isUghbinding());
        af.setUghbinding(true);
        assertTrue(af.isUghbinding());
    }

    @Test
    public void testDocstruct() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setDocstruct(null);
        assertEquals("topstruct", af.getDocstruct());

        af.setDocstruct("different value");
        assertEquals("different value", af.getDocstruct());
        
    }

    @Test
    public void testMetadata() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        
        af.setMetadata("value");
        assertEquals("value", af.getMetadata());
    }

    @Test
    public void testIsdoctype() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        af.setIsdoctype(null);
        assertNotNull(af.getIsdoctype());
        
        af.setIsdoctype("value");
        assertEquals("value", af.getIsdoctype());
    }

    @Test
    public void testIsnotdoctype() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        
        af.setIsnotdoctype(null);
        assertNotNull(af.getIsnotdoctype());
        
        af.setIsnotdoctype("value");
        assertEquals("value", af.getIsnotdoctype());
    }

    @Test
    public void testShowDependingOnDoctype() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        
        af.setIsnotdoctype("");
        af.setIsdoctype("");
        assertTrue(af.getShowDependingOnDoctype());
        
        pfk.setDocType("type");
        af.setIsdoctype("other");
        assertFalse(af.getShowDependingOnDoctype());
        
        pfk.setDocType("not");
        af.setIsnotdoctype("not");
        assertFalse(af.getShowDependingOnDoctype());

        pfk.setDocType("type");
        af.setIsdoctype("type");
        assertTrue(af.getShowDependingOnDoctype());
        
    }

    @Test
    public void testAutogenerated() {
        ProzesskopieForm pfk = new ProzesskopieForm();
        AdditionalField af = new AdditionalField(pfk);
        
        assertFalse(af.getAutogenerated());
        af.setAutogenerated(true);
        assertTrue(af.getAutogenerated());
    }

}
