name: Publish Release Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn clean verify -U -P release-build
      - name: Rename WAR
        run: mv target/*.war target/goobi.war
      - name: Create Docker workflow archive
        run: |
           set -e
           
           WORKDIR=/tmp/workflow
           TAG=${{ github.ref_name }}
           
           mkdir -p ${WORKDIR}/goobi/{config,plugins/{administration,command,dashboard,export,generic,GUI,import,opac,statistics,step,theme,validation,workflow}} \
                    ${WORKDIR}/tomcat \
                    ${WORKDIR}/db/{setup,mysql}
           
           cp -r ./install/config/* ${WORKDIR}/goobi/config
           mv ${WORKDIR}/goobi/config/goobi_config.properties \
              ${WORKDIR}/goobi/config/goobi_config.user.properties
           
           cp ./install/db/goobi_blank.sql ${WORKDIR}/db/setup/000_dump.sql
           
           cp docker-compose.yml ${WORKDIR}/
           sed -i "s/goobi-workflow:latest/goobi-workflow:${TAG}/g" \
             ${WORKDIR}/docker-compose.yml
           
           tar -czvf goobi-workflow-docker.tar.gz -C ${WORKDIR} .
      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            **/target/*.war
            install/*
